### ISSUE TITLE
When SAS is taken down while running traffic, excessive error logs are generated

### ISSUE THREAD

**Issue by dtheobald** [Metaswitch/sas-client#46]
SAS went down during a soak test and caused all nodes to fill up their root partition with SAS connection error logs. This wouldn't be too worrisome if the errors were being generated at a reasonable rate, but they were coming out as fast as each node could generate them (i.e. 1+ per millisecond).

I made this change over in CC land - https://github.com/ClearwaterCore/sas-client/compare/Metaswitch:946acb484870a75f83e42540391c11be32e0464a...CC_badsas-63

I can submit a pull request, if you find that change satisfactory.

**Comment by jw2** [comment]
Hi Doug,

-  I don't think that the message queue size check will ever trigger because the queue is limited to 1000 messages.  Also, my feeling is that the queue itself should be handling this sort of logic.
-  Your indentation doesn't match the rest of the code.

If you can address those, I'd be happy for you to submit a pull request.

Cheers,
Jim.

**Comment by rkd-msw** [comment]
@dtheobald, was this fixed by https://github.com/Metaswitch/sas-client/pull/47 (and should it be closed)?

**Comment by eleanor-merry** [comment]
Fixed in #47
